# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls
          git --version
          git config --unset --global credential.helperselector
          git config credential.helper store
          git config --global user.email "penchikalanaresh62@gmail.com"
          git config --global user.name "nareshpenchikala"
          git config --global user.password "LAKSHMISUHASINI"
          git config --global github.token "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"
          echo "list for-push" | strace /usr/lib/git-core/git-remote-https my
          mkdir dummy
          cd dummy
          git init
          git remote add origin https://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@github.com/nareshpenchikala/check.git
          git remote -v
          git pull origin main
          git checkout -b main
          ls
          cd ../
          rsync -a --exclude 'dummy' * dummy/
          cd dummy
          git add .
          git commit -m "new files added"
          git push https://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@github.com/nareshpenchikala/check.git HEAD:main
          cd ../
          rm -rf dummy
